
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

import '@fortawesome/fontawesome-free/css/all.min.css';

import "./globals.css";


export const metadata = {
  title: "Mansi Computer Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
